channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
  - pyg

dependencies:
  # Minimal dependencies for the competition
  - python=3.8
  - scip=7.0.3
  - ecole=0.7.3
  - numpy
  - pyscipopt

  # additional conda dependencies go here
  - scipy
  - joblib
  - ConfigSpace
  - filelock
  #- pytorch=1.9.1
  #- cudatoolkit=11.1
  #- pytorch_geometric
  - pytorch-lightning

  # additional pip dependencies go here
  #- pip
  #- pip:
    #- pytorch-lightning
    #- torch-scatter -f https://data.pyg.org/whl/torch-1.9.1+cu111.html
    #- torch-sparse -f https://data.pyg.org/whl/torch-1.9.1+cu111.html
    #- torch-geometric

  # Please send us a snapshot of your environment as well
  # to help us troubleshoot potential issues
  # conda env export --no-builds
